# src/p2_behavioral_risk/config.py

"""
P2 configuration for Hackathon Option 2.

Scope:
    Vision-only / ResNet18 behavioral probing.

Keep this file small. Values here are implementation limits and
thresholds, not research-calibration gates.
"""

# ---------------------------------------------------------------------------
# Vision probe configuration
# ---------------------------------------------------------------------------

# Maximum number of behavioral probes generated by P2.
BOUND_N = 32

# ResNet18 / ImageNet input configuration.
VISION_NUM_CLASSES = 1000
VISION_IMAGE_SIZE = 224

# ---------------------------------------------------------------------------
# Risk thresholds
# ---------------------------------------------------------------------------

# MRS verdict thresholds.
MRS_PASS_MAX = 34.0
MRS_REVIEW_MAX = 69.0
MRS_FAIL_MIN = 70.0

# ---------------------------------------------------------------------------
# MRS weights
# ---------------------------------------------------------------------------

# Non-quantized:
# MRS = 40*S_static + 35*P_tamper + 25*S_behavior
MRS_STATIC_WEIGHT = 40.0
MRS_TAMPER_WEIGHT = 35.0
MRS_BEHAVIOR_WEIGHT = 25.0

# Quantized:
# MRS = 55*S_static + 45*P_tamper
MRS_QUANT_STATIC_WEIGHT = 55.0
MRS_QUANT_TAMPER_WEIGHT = 45.0

# ---------------------------------------------------------------------------
# STRIP normalization
# ---------------------------------------------------------------------------

# D4 normalization:
#
# deviation = H_median - H_STRIP
# Z = deviation / (1.4826 * H_MAD)
# S_behavior = min(1, max(0, Z) / 3)
STRIP_Z_SCALE = 3.0
MAD_SCALE = 1.4826
